// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK_uISChqfl7f5Nb0DLlRTmFIJMvcfEig',
    appId: '1:314499425729:android:8c482da546538115cafb40',
    messagingSenderId: '314499425729',
    projectId: 'globalchatapp-dcc19',
    storageBucket: 'globalchatapp-dcc19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDacwSAWWTd_NbFMbYlQmLNg6nVvt3lwo0',
    appId: '1:314499425729:ios:22c3880886fb52d5cafb40',
    messagingSenderId: '314499425729',
    projectId: 'globalchatapp-dcc19',
    storageBucket: 'globalchatapp-dcc19.appspot.com',
    iosBundleId: 'com.example.globatchatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlcBnBy-5xi1wT1uCjjSAZm50PoBEOdy8',
    appId: '1:314499425729:web:2404abed820f42adcafb40',
    messagingSenderId: '314499425729',
    projectId: 'globalchatapp-dcc19',
    authDomain: 'globalchatapp-dcc19.firebaseapp.com',
    storageBucket: 'globalchatapp-dcc19.appspot.com',
  );

}